Houdini.env
zync/zync-houdini pull request #1
Opened 2016-12-02 08:20 UTC by tokejepsen

Hey,

This PR is also more a request to change how you install the plugins for Houdini. Currently you are overriding any environment set prior to launching Houdini. Use ```$HOUDINI_PATH``` will inherit the existing environment and append to it.

NOTE: I haven't tested this on OSX and Linux, so I don't know whether the path separator ```;``` needs to change per platform.

2016-12-05 10:17 UTC, pawloKoder commented
Thanks for pointing this! Changes in installer are done and pending release.

2016-12-05 10:20 UTC, pawloKoder requested changes
In Zync we have a convention of bumping the plugin version even when changing docs. Please do so.

2016-12-06 12:42 UTC, tokejepsen commented
Think this is done?

2016-12-06 16:10 UTC, pawloKoder approved these changes

2016-12-07 13:45 UTC, merged